---
abstract: 'Perl API to Houdini, a zero-dependency C web escaping library'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::Exception: '0'
  Test::More: '0'
  perl: '5.006'
  utf8: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Escape-Houdini
provides:
  Escape::Houdini:
    file: lib/Escape/Houdini.pm
    version: v0.3.3
requires:
  DynaLoader: '0'
  Exporter: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Escape-Houdini/issues
  homepage: https://github.com/yanick/Escape-Houdini
  repository: https://github.com/yanick/Escape-Houdini.git
version: 0.3.3
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Askar Timirgazin <anotheroneackap@gmail.com>'
  - 'Mike Doherty <doherty@cs.dal.ca>'
  - 'Tony Cook <tonyc@cpan.org>'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
